
development:
  adapter: postgresql
  encoding: unicode
  database: product-test_development
  pool: 5
  username: product-test
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: product-test_test
  pool: 5
  username: product-test
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: product-test_production
  pool: 5
  username: product-test
  password:
